### ISSUE TITLE
add file uploads to the family registration form

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#1]
### as a developer, I need to add homestudy file uploads to the family registration form so that users can more easily submit documents
---

### Notes

The file shouldn't be uploaded automatically, it should instead be emailed to the correct CSC Email Contact.

### Tasks

- [ ] update the family registration form to allow users to attach their homestudy while registering
- [ ] if a file of the wrong type is uploaded, the user will be presented with an error

### Definition of Done

- [ ] uploading a Word document or PDF homestudy will be successful
- [ ] attempting to upload a non-Word and non-PDF homestudy will display an error for the user

**Comment by bchiaruttini** [comment]
per jared: #1  is dependent on #7, and should be taken care of by me.
