### ISSUE TITLE
admin can't access the admin UI in Internet Explorer

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#101]
### as a developer, I need to fix the bug preventing IE users from accessing the admin UI so that MARE staff doesn't have to worry about which machine they access it from
---

### Tasks

- [ ] determine what's causing the bug
- [ ] fix the issue ( if possible )

### Definition of Done

- [ ] users logged in as administrators can access the admin UI in Internet Explorer

### Notes

we need more information about which version of IE is running into the issue, and if it's worth fixing

**Comment by bchiaruttini** [comment]
IE version is 11.0.9600.19100  , which is most current as of 8/20/2018
