### ISSUE TITLE
event attendees report

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#103]
### as a developer, I need to create the event attendees reports so that MARE staff can easily determine who's attending events
---

### Tasks

- [ ] create a reports tab in the account area for admin users
- [ ] add a toggle to access event reporting
- [ ] add a list of all events
- [ ] add a button to each event that will download an easy to read list of attendees for the event

### Definition of Done

- [ ] admin users have access to a reports tab on their account page
- [ ] admin users can access event reporting through the reports tab
- [ ] admin users can press a button to download the attendees for an event
