### ISSUE TITLE
update language on register a family's homestudy form

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#104]
### as a developer, I need to update the language on the register a family's homestudy form to remove unneeded directions
---

### Tasks

- [ ] remove the following text

>Only social workers can register families' homestudies.

- [ ] and add period after

>If you're a social worker, either log in or create an account.

### Definition of Done

- [ ] the text has been updated

**Comment by bchiaruttini** [comment]
could be related to 154

**Comment by bchiaruttini** [comment]
no longer necessary
