### ISSUE TITLE
allow gender to be set from the family account page

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#106]
### as a developer, I need to fix a bug preventing gender from being set from the family account page so that users can update the field at will
---

### Tasks

- [ ] store the gender information with the rest of the form data being submitted to the server when a family's user information is updated
- [ ] store changes to the gender field in the user's model

### Definition of Done

- [ ] when a family updates the *gender* field from their account, the changes persist to the databse

**Comment by bchiaruttini** [comment]
not sure this is still neccesary?

**Comment by n-devr** [comment]
I can investigate if it's been addressed or not. I don't remember working on this functionality so I would guess it's still outstanding.

**Comment by bchiaruttini** [comment]
on hold while figure out SOGIE collection plan
