### ISSUE TITLE
migrate child history

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#11]
### as a developer, I need to migrate child history entries so that MARE can see changes to family models prior to the site go-live
---

### Tasks

- [ ] write scripts to migrate all child history entries
- [ ] ensure each history entry from the old system has a corresponding entry in the new system
- [ ] ensure any field changes in the old system are captured in the new system even if the fields don't line up
- [ ] ensure all dates are being recorded correctly

### Definition of Done

- [ ] all child changes prior to the go-live are appearing in each child record

**Comment by bchiaruttini** [comment]
per jared 8/6: #10 and #11 are migration tasks and should be handled by me
