### ISSUE TITLE
fix readability issue with internal notes

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#112]
### as a developer, I need to update internal notes when they are displayed at the bottom of the Child or Family models so that CSCs can read them more easily
---

### Tasks

- [ ] update Keystone's display of Relationship text fields to prevent character encoding.

### Definition of Done

- [ ] whitespace is preserved in Internal Notes Relationship fields displayed at the bottom of Child and Family models
- [ ] special characters aren't encoded in Internal Notes Relationship fields displayed at the bottom of Child and Family models

### Notes

With support ending for Keystone 0.3.x, this will need to wait until we've upgraded to the 4.x branch.  Once done, the fix must be handed in the [Keystone code](https://github.com/keystonejs/keystone)

**Comment by autoboxer** [comment]
This is a duplicate of #76.
