### ISSUE TITLE
prevent multiple inquiry submissions

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#114]
### as a developer, I need to disable the submit button after submission to prevent users from mistakenly submitting multiple versions of the same inquiry
---

### Tasks

- [ ] disable the submit button on submission only if form validation passes

### Definition of Done

- [ ] submitting an inquiry and having client-side form validation fail will not disable the submit button
- [ ] submitting an inquiry and having client-side form validation pass will disable the submit button
