### ISSUE TITLE
fix referring page routing

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#115]
### as a developer, I need to update pages to send referrer information when appropriate so that users who are prompted to take certain actions are redirected back to the page they were referred from
---

### Tasks

- [ ] update the [social worker child registration form](http://development.adoptions.io/page/register-a-child) to pass referrer information when an anonymous user clicks on the **Create an account** button
- [ ] update the [social worker family homestudy registration form](http://development.adoptions.io/page/register-a-familys-homestudy) to pass referrer information when an anonymous user clicks on the **Create an account** button
- [ ] update the details of [MARE adoption parties and information events](http://development.adoptions.io/events/adoption-parties/) to pass referrer information when an anonymous user clicks on the **Create an account** button
- [ ] update the details of [fundraising events](http://development.adoptions.io/events/fundraising-events/) to pass referrer information when an anonymous user clicks on the **Create an account** button
- [ ] handle referrer information on redirect from the create an account page.  Note that page referral code was removed, but can be round in early versions of middleware.js

### Definition of Done

- [ ] creating an account when referred from the [social worker child registration form](http://development.adoptions.io/page/register-a-child) redirects the user back to the [social worker child registration form](http://development.adoptions.io/page/register-a-child)
- [ ] creating an account when referred from the [social worker family homestudy registration form](http://development.adoptions.io/page/register-a-familys-homestudy) redirects the user back to the [social worker family homestudy registration form](http://development.adoptions.io/page/register-a-familys-homestudy)
- [ ] creating an account when referred from the details of [MARE adoption parties and information events](http://development.adoptions.io/events/adoption-parties/) redirects the user back to the details of that MARE adoption parties and information event
- [ ] creating an account when referred from the details of [fundraising events](http://development.adoptions.io/events/fundraising-events/) redirects the user back to the details of that fundraising event
- [ ] creating an account without referrer page information will keep the user on the create an account page
- [ ] navigating between Backbone routes on the account page by selecting a different user type to register preserves the referrer information in the URL
- [ ] protected routes are still handled as they were before
- [ ] non-registration page routing is still handled as it was before
