### ISSUE TITLE
update required fields in the Child model

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#117]
### as a developer, I need to make fields required in the Child model in an effort to prevent CSCs from losing work when models fail to save
---

### Tasks

- [ ] make the social worker field required
- [ ] make the recruitment worker field required

### Definition of Done

- [ ] the social worker field is required
- [ ] the recruitment worker field is required

**Comment by bchiaruttini** [comment]
Initial solution to this caused other problematic behavior, but still need to address this issue.

**Comment by bchiaruttini** [comment]
does not appear to be causing issues currently.
