### ISSUE TITLE
sibling group inquiries should show up for all chidlren

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#118]
### as a CSC I need inquiries for sibling groups to be associated with each child in the sibling group so that I don't lose inquiry details
---

### Tasks

- [ ] update the service that processes inquiry submissions to handle arrays ( sibling groups )

### Definition of Done

- [ ] inquiring about a sibling group will add each sibling to the **child** field in the inquiry
- [ ] inquiries about a sibling group will appear at the bottom of each child record from that sibling group
