### ISSUE TITLE
updating a child in a sibling group should replicate data to the other siblings

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#119]
### as a CSC, I need edits to some fields in a child record to automatically change those fields in the child's siblings so that data stays consistent and I don't need to manually find and update each child
---

### Tasks

- [x] update the child post-save hook to update the following fields across siblings: **family constellation**, **social worker**, and **activate to website**
- [ ] finish #213 as well

### Definition of Done

- [x] updating the **family constellation** field in a child model which is part of a sibling group will propagate that change to the child's siblings
- [x] updating the **social worker** field in a child model which is part of a sibling group will propagate that change to the child's siblings
- [x] updating the **activate to website** field in a child model which is part of a sibling group will propagate that change to the child's siblings

### Notes

The post-save hook for children calls `updateSiblingGroup()` which builds the list of siblings to update, and calls `applySiblingGroupToChild(...)`.  The fields to replicate across siblings should be passed in to that function.  `isCurrentChildInNewSiblingGroup` will need to be updated with a check for all passed in field values, then the fields will need to be updated.

Alternatively, the function to update the sibling fields could be done further down in the promise chain of `updateSiblingGroup()`, which would cause multiple saves and the change history to be generated in two separate entries, but make the code less tightly coupled.

**Comment by bchiaruttini** [comment]
Constellation and Social Worker assignment working properly.  Activate to web button working correctly across siblings, however is not actually removing from the web

**Comment by bchiaruttini** [comment]
tested 11/12

**Comment by autoboxer** [comment]
This issue was reopened to change the logic for replication.  The fields:

*recommended family constellations*
*is child visible in the gallery*
*adoption worker*
*recruitment worker*

should only replicate to siblings in a sibling group, not to all siblings.

**Comment by bchiaruttini** [comment]
this was previously addressed but not currently working in production or development.
