### ISSUE TITLE
migrate file attachments

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#12]
### as a developer, I need to migrate family and child attachment entries so that MARE can access all documents from each respective model
---

### Tasks

- [ ] update the child model to handle as many attachments as are needed
- [ ] update the family model to handle as many attachments as are needed
- [ ] write scripts to migrate all attachment bindings
- [ ] move all existing attachments to the correct s3 bucket and folder
- [ ] ensure all attachments have consistent naming, and adjust any that don't
- [ ] ensure all attachments are showing up in each family and child record

### Definition of Done

- [ ] all child attachments are appearing in each family record
- [ ] all family attachments are appearing in each family record

**Comment by bchiaruttini** [comment]
per jared 8/6: #12  is dependent on #7, and should be taken care of by me
