### ISSUE TITLE
Internal notes should save across sibling groups

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#120]
### as a CSC, I need internal notes saved for a child record to automatically generate identical notes for the child's siblings so that I don't need to manually create the same note each child
---

### Tasks

- [ ] add an internal note post-save hook to find siblings for the target child if any exist, and generate identical notes for them
- [ ] *alternate approach:* make the **child** field a **many: true** field.

### Definition of Done

- [ ] creating an internal note for a child who is part of a sibling group will show that note ( or a duplicate of that note, depending on which approach is taken ) at the bottom of each siblings record

**Comment by autoboxer** [comment]
@bchiaruttini, there are two ways to handle this:

1. create a duplicate note for each child
2. allow multiple children to be selected as the target for a note

which would you prefer?

**Comment by bchiaruttini** [comment]
Assuming the duplicate note would  happen automatically that would be preferred.

**Comment by bchiaruttini** [comment]
And to clarify, this would only be for sibling who are to be placed together.

**Comment by bchiaruttini** [comment]
Was complete however discovered error:  It also duplicates internal notes for “have contact with” siblings in addition to “must be placed with” siblings.
