### ISSUE TITLE
store phone numbers using a consistent format

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#14]
### as a developer, I need to update how we store phone numbers so that we have one consistent format in the database
---

### Tasks

- [x] update all form processing to store phone numbers in the format **xxx-xxx-xxxx**
- [ ] update all phone numbers currently stored in the database to match the format **xxx-xxx-xxxx**

### Definition of Done

- [x] submitting a phone number through any form on the website will cause it to be stored in the format **xxx-xxx-xxxx**
- [x] phone numbers for every record currently in the system are in the format **xxx-xxx-xxxx**

### Notes

See [this article][1] for phone number regular expressions

[1]: http://stackoverflow.com/questions/123559/a-comprehensive-regex-for-phone-number-validation

**Comment by bchiaruttini** [comment]
per jared 8/6: #14 is fine to work on

possibly duplicate of #4?

**Comment by bchiaruttini** [comment]
tested by MARE, neptune incorporating Jared feedback.
