### ISSUE TITLE
fix spelling error in inquiry emails

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#17]
### as a developer, I need to fix the spelling of inquiry at the bottom of the general and child inquiry emails that go to MARE so MARE doesn't look unprofessional
---

### Tasks

- [x] change the spelling from inquiriy to inquiry at the bottom of general inquiry emails to MARE
- [x] change the spelling from inquiriy to inquiry at the bottom of child inquiry emails to MARE

### Definition of Done

- [x] inquiry is spelled correctly in general inquiry email to MARE
- [x] inquiry is spelled correctly in child inquiry email to MARE

#### setup

1. have Jared turn on inquiry emails to MARE
2. log in as an **administrator**
3. set the **general inquiry** staff email contact to yourself
4. set the **child inquiry** staff email contact to yourself
5. log out

#### 1. check that the spelling error has been corrected in the general inquiry email

1. log in as a **family**
2. submit a general inquiry
3. ensure inquiry in spelled correctly at the bottom of the email

#### 2. check that the spelling error has been corrected in the child inquiry email

1. log in as a **family**
2. submit a child inquiry
3. ensure inquiry in spelled correctly at the bottom of the email

#### final steps

1. have Jared turn off inquiry emails to MARE

### Test Accounts

testfamily@mare.com
asdf
