### ISSUE TITLE
update Boolean to support default: true

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#174]
### As a developer, I need to update the Boolean field type to support **default: true** so that checkboxes can be checked by default
---

### Tasks

- [ ] update the Keystone 4 branch to handle Booleans with **default: true** correctly
- [ ] update any related unit tests
- [ ] update Keystone in MARE package.json to point to the updated Keystone commit

### Definition of Done

- [ ] Keystone models with Boolean fields that have **default: true** will be checked by default in the initial creation modal
- [ ] Keystone models with Boolean fields that have **default: true** will remain checked after initial save if no changes are made
