### ISSUE TITLE
fix today option for Dates

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#177]
### As a CSC, I need the today option for Date fields to work correctly so that we can accurately represent meaningful points in time correctly
---

### Notes

When using the today button after 8:00pm EST, it uses tomorrows date

### Tasks
- [ ] update the Keystone 4 branch to handle Date storage correctly despite the server or client browser timezone
- [ ] update any related unit tests
- [ ] update Keystone in MARE package.json to point to the updated Keystone commit

### Definition of Done
- [ ] clicking the **today** button in the admin UI will correctly assign the current date, regardless of when the button is clicked ( it would be a good idea to test early in the morning and late at night )
