### ISSUE TITLE
fix Dates across the Admin UI

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#178]
### As a CSC, I need dates to display in a readable format so that we can quickly and accurately identify meaningful points in time
---

### Notes

Before we fix the dates in the list view, we can temporarily adjust the column widths to accomodate longer month names

### Tasks

- [x] allow dates to use a formatted option in disabled fields
- [ ] allow dates to use a formatted option in meta createdDate updatedDate fields
- [ ] allow dates to use formatted options in model list views
- [x] allow dates to use formatted options when showing model date fields
- [x] allow dates to use formatted options in date placeholders
- [ ] update any related unit tests
- [ ] update Keystone in MARE package.json to point to the updated Keystone commit

### Definition of Done

- [ ] disabled fields use the format 'MM/DD/YYYY'
- [ ] createdDate and updatedDate fields use the format 'MM/DD/YYYY'
- [ ] model lists showing date columns use the format 'MM/DD/YYYY'
- [ ] dates in models use the format 'MM/DD/YYYY'
- [ ] date placeholders in models use the format 'MM/DD/YYYY'

**Comment by joesmare** [comment]
@n-devr I think this was addressed in the last upgrade. There are some specific notes that I cannot verify. Could you take a look and tell me if this still needs to be open?

**Comment by bchiaruttini** [comment]
does not appear to still present any issues so closing.
