### ISSUE TITLE
update child inquiry email to MARE

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#18]
### as a developer, I need to update the email to MARE that's generated when child inquiries are created through the website so that CSCs will be able to respond more easily by clicking 'reply' and won't respond with sensitive information about a child.
---

### Tasks

- [x] group the fields in a more readable way
- [x] remove child's last name
- [x] have email originate from inquirer
- [x] remove photolisting page
- [x] add family email
- [x] add family stage in process
- [x] add the mare logo to the email header

### Definition of Done

- [x] the fields are grouped in a readable way
- [x] the email originates from the inquirer
- [x] the photolisting page and child's last name fields are not present in the email
- [x] the family email and stage in the process are present in the email
- [x] the mare logo is present in the header of the email

#### setup

1. have Jared turn on inquiry emails to MARE
2. log in as an **admin**
3. set the **child inquiry** staff email contact to yourself
4. set all **region contacts** to yourself
5. log out

#### 1. single child inquiry by a family

1. log in as a **family** and navigate to [this page](http://development.adoptions.io/forms/information-request?registrationNumber=6826)
2. fill out the required information and click **submit**
3. note in the email that the following is true
    a. the child's last name is not present
    b. clicking **reply** in the email will respond to the family's email address
    c. the child's photolisting page is not present
    d. the family's **stage** information is present
    e. the MARE logo is present at the top of the email and loads instantly
    f. the fields are grouped in a readable way

#### 2. sibling group inquiry by a family

1. navigate to [this page](http://development.adoptions.io/forms/information-request?registrationNumber=5644,5645)
2. fill out the required information and click **submit**
3. note in the email that the following is true
    a. all child last names are not present
    b. clicking **reply** in the email will respond to the family's email address
    c. all child photolisting pages are not present
    d. the family's **stage** information is present
    e. the MARE logo is present at the top of the email and loads instantly
    f. the fields are grouped in a readable way

#### 3. single child inquiry by a social worker

1. log in as a **social worker** and navigate to [this page](http://development.adoptions.io/forms/information-request?registrationNumber=6826)
2. fill out the required information and click **submit**
3. note in the email that the following is true
    a. the child's last name is not present
    b. clicking **reply** in the email will respond to the social worker's email address
    c. the child's photolisting page is not present
    e. the MARE logo is present at the top of the email and loads instantly
    f. the fields are grouped in a readable way

#### 4. sibling group inquiry by a social worker

1. navigate to [this page](http://development.adoptions.io/forms/information-request?registrationNumber=5644,5645)
2. fill out the required information and click **submit**
3. note in the email that the following is true
    a. all child last names are not present
    b. clicking **reply** in the email will respond to the social worker's email address
    c. all child photolisting pages are not present
    e. the MARE logo is present at the top of the email and loads instantly
    f. the fields are grouped in a readable way

#### final steps

1. have Jared turn off inquiry emails to MARE

### Test Accounts

testfamily@mare.com
asdf

testsocialworker@mare.com
asdf
