### ISSUE TITLE
inquiries should save across sibling groups

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#181]
### as a CSC, I need inquiries saved for a child record to only automatically add the other siblings if they must be placed together
---

### Tasks

- [ ] update the logic that automatically adds siblings to an inquiry so that it only happens if they must be placed together.

### Definition of Done

- [ ] an inquiry created for a child should add their siblings if they must be placed together
- [ ] an inquriy created for a child should not add their siblings if they are not selected to be placed together
