### ISSUE TITLE
update general inquiry email to MARE

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#19]
### As a developer I need to update the email to MARE that's generated when general inquiries are created through the website so that CSCs will be able to respond more easily by clicking 'reply' and won't respond with sensitive information about a child.
---

### Tasks

- [x] group the fields in a more readable way
- [x] have email originate from inquirer
- [x] add family email
- [x] add family date of birth
- [x] add family gender
- [x] add family ethnicity
- [x] add family stage in process
- [x] add family social worker
- [x] add the mare logo to the email header

### Definition of Done

- [x] the fields are grouped in a readable way
- [x] the email originates from the inquirer
- [x] the family email, date of birth, gender, ethnicity, stage in the process, and social worker are present in the email
- [x] the MARE logo is present in the header of the email

#### setup

1. have Jared turn on inquiry emails to MARE
2. log in as an **admin** and set the **general inquiry** staff email contact to yourself
3. log out

#### 1. general inquiry by a family

1. log in as a **family**
2. navigate to [this page](http://development.adoptions.io/forms/information-request)
3. click on **general inquiry**, fill out the required information, then click **submit**
4. note in the email that the following is true
    a. the family's date of birth is present
    b. the family gender is present
    c. the family ethnicity is present
    d. the family stage is present
    e. the family social worker is present
    f. clicking **reply** in the email will respond to the family's email address
    g. the MARE logo is present at the top of the email and loads instantly
    h. the fields are grouped in a readable way

#### 1. general inquiry by a social worker

1. log in as a **social worker**
2. navigate to [this page](http://development.adoptions.io/forms/information-request)
3. click on **general inquiry**, fill out the required information, then click **submit**
4. note in the email that the following is true
    a. clicking **reply** in the email will respond to the family's email address
    b. the MARE logo is present at the top of the email and loads instantly
    c. the fields are grouped in a readable way

#### final steps

1. have Jared turn off inquiry emails to MARE

### Test Accounts

testfamily@mare.com
asdf

testsocialworker@mare.com
asdf
