### ISSUE TITLE
restrict file upload MIME types

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#2]
### as a developer, I need to restrict the MIME types for uploaded files so that we can ensure all documents are stored in an acceptable format
---

### Tasks

- [ ] update family attachments to accept only **.pdf** and **.doc** MIME types
- [ ] update child attachments to accept only **.pdf** and **.doc** MIME types

### Definition of Done

- [ ] files can only be attached to family models if they are Word documents or PDF files
- [ ] files can only be attached to child models if they are Word documents or PDF files

**Comment by bchiaruttini** [comment]
per jared 8/6: #2 is dependent on #7, and should be taken care of by me.
