### ISSUE TITLE
remove legal disclosure language from the event registration form

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#20]
### as a developer, I need to remove the legal disclosure language on bottom of event registration form when logged in as any type of user to ensure users aren't seeing information they shouldn't be
---

### Tasks

- [x] remove legal disclosure language for logged in site visitors
- [x] remove legal disclosure language for logged in social workers
- [x] remove legal disclosure language for logged in families

### Definition of Done

- [ ] the legal language is no longer present for logged in site visitors
- [ ] the legal language is no longer present for logged in social workers
- [ ] the legal language is no longer present for logged in families

#### 1. the legal language has been removed for site visitors

1. log in as a **site visitor**
2. navigate to the [this event](http://development.adoptions.io/events/adoption-parties/2018-beanstalk-adoption-party) 
3. click **register** and note that the legal language is not present at the bottom of the form

#### 2. the legal language has been removed for social workers

1. log in as a **social worker**
2. navigate to the [this event](http://development.adoptions.io/events/adoption-parties/2018-beanstalk-adoption-party) 
3. click **register** and note that the legal language is not present at the bottom of the form

#### 3. the legal language has been removed for families

1. log in as a **family**
2. navigate to the [this event](http://development.adoptions.io/events/adoption-parties/2018-beanstalk-adoption-party) 
3. click **register** and note that the legal language is not present at the bottom of the form

### Test Accounts

testsitevisitor@mare.com
asdf

testfamily@mare.com
asdf

testsocialworker@mare.com
asdf
