### ISSUE TITLE
migrate from Cloudinary to AWS S3

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#218]
### As a shareholder, I need to migrate our image service to an AWS S3 instance so that we can reduce the cost of the site.
---

### tasks

- [ ] set up S3 buckets for development, staging, and production
- [ ] set up https and encryption for the S3 buckets
- [ ] set up security policies restricting access to only calls from the site
- [ ] set up Cloudfront for image cacheing and CDN
- [ ] migrate all images to the S3 buckets
- [ ] update all admin UI fields to use the file type and point to the new image locations
- [ ] update the admin UI to provide an image preview
- [ ] turn off Cloudinary service through Cloudinary
- [ ] remove Cloudinary setup and config from the application

### related issues

#52
