### ISSUE TITLE
integrate our email system with Mailchimp

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#22]
### as a developer, I need to integrate our email system with MailChimp so we can manage MailChimp subscriber lists from the Keystone application
---

### Tasks

- [x] create an API to integrate with MailChimp
  - [x] get subscriber lists (all)
  - [x] get subscriber list by Id
  - [x] add subscriber to list
  - [x] modify subscriber (update email)
  - [x] remove subscriber
- [x] create Keystone Models to describe MailChimp subscriber lists
- [x] add relationship fields to User models to track which lists they're subscribed to
- [x] build the mailing list preferences view on user creation
- [x] update our subscriber lists if someone unsubscribes from a MailChimp newsletter
- [x] handle corner cases, like if we need to add subscribers to MailChimp but the mailing list doesn't exist

### Definition of Done

- [x] email registration changes on the website are propagated to MailChimp subscriber lists
- [x] users can review and update their subscription preferences from the website

**Comment by joesmare** [comment]
This issue has been completed. There is one adjunct piece that will be added as a separate story.
