### ISSUE TITLE
Allow anonymous users to register for fundraising events

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#232]
### As an anonymous user, I need to be able to register for fundraising events so that I won't be discouraged by the account creation process
---

### Tasks
- [ ] add new checkbox in fundraising events called **allow unregistered user registration**.  If the functionality should exist for all fundraising events, skip this step
- [ ] update the Express view to load the correct form template based on the user and state of the **allow unregistered user registration** checkbox
- [ ] create the unregistered user registration template or edit the existing registration template to add any new fields (first/last name most likely, maybe address, maybe additional info) - get list from Bridget and Joe
- [ ] handle form submission
- [ ] send an email about the new registration

### Definition of Done

- [ ] anonymous users can register for fundraising events that allow it
- [ ] an email is sent to the correct staff email contact with all the registration details

**Comment by bchiaruttini** [comment]
needs exploration if still needed with give lively and salesforce.
