### ISSUE TITLE
add donations to the account page

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#25]
### as a developer, I need to add and populate a donations list tab for all user account pages so that users can view previous donations and current donation subscriptions without contacting MARE or accessing Stripe
---

### Tasks

- [ ] create a donations tab for all users
- [ ] add past donations to the tab with the date and amount, as well as an in care of information if available
- [ ] add current and past recurring donations to the tab with start date, end date, amount, and care of information if available

### Definition of Done

- [ ] each user type has a donations tab in their account page
- [ ] users can see details of both past donations as well as current recurring donations

**Comment by bchiaruttini** [comment]
on hold due to salesforce migration
