### ISSUE TITLE
add inquiry information to the account page

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#27]
### as a developer, I need to add and populate an inquiry tab for all user account pages so that users can view the progress of their inquiries without contacting MARE
---

### Tasks

- [ ] create an inquiry tab for all users in their account page
- [ ] populate the tab with their inquiries, as well as information they should be seeing **[Lisa, I need more input here]**, and the status
- [ ] **[Lisa, it's possible to note additional information we need, and allow them to enter it directly from their account page, would this be valuable functionality?]**
- [ ] create an inquiry details modal that shows detailed information of their progress and submitted information

### Definition of Done

- [ ] each user type has an inquiry tab on their account page
- [ ] users can see all their inquiries as well as basic details in the initial list view
- [ ] users can click into each inquiry to bring up detailed information about progress and the information they entered
- [ ] **[possible, but need Lisa's feedback first]** users can update or add new information to an inquiry

**Comment by lisa** [comment]
@autoboxer Also on this issue too, I think you mean another Lisa. :)

**Comment by bchiaruttini** [comment]
Ignoring most of what is written above, when family is logged in, under My Information, need sub tab entitled Inquiries with a question mark icon.  Once selected, should reveal list of all inquiries associated with the family record, showing the following fields: Date Taken On (but titled Date Submitted), Inquiry Type, Children, and Inquiry Method.  Should order with most recent first, and does not need to be sortable.

Q: Is it possible for name under Children to link to their web profile?

**Comment by bchiaruttini** [comment]
Additional note: confirming current functionality is such that if you try to access child profile that you don't the permissions for, it just defaults to general child profile page.

**Comment by bchiaruttini** [comment]
reference #706 for convo on SW inquiries.

**Comment by n-devr** [comment]
@bchiaruttini other than `active`, which child statuses should still display a link to allow the user's to view their profile in the gallery?

**Comment by bchiaruttini** [comment]
@n-devr 
1.) active is only child status that should display a link
2.) no other fields necessary, although I believe "on behalf of" is answerable by two distinct fields...the text box manual entry or the registered family name

**Comment by n-devr** [comment]
Couple more questions @bchiaruttini :

1. Do we want to show inquiries that were submitted on behalf of families?  E.g. Social Worker X submits an inquiry on behalf of Family Y. Family Y logs in to their account, should they see that Inquiry in the list?
    - If so, should we include a line with the SW who submitted the inquiry for them?
2. Do we want to indicate whether or not the inquiry has been accepted?

**Comment by bchiaruttini** [comment]
Easy answers - no to both.  thanks.
