### ISSUE TITLE
add videos to success stories

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#29]
### as a developer, I need to allow MARE to add videos to success stories so they can provide more dynamic content on the website
---

### Tasks

- [ ] add a video field to the success story model
- [ ] display the video on the website for any success stories that have one
- [ ] fix styling on the page to look good across breakpoints for success stories with a video
- [ ] fix styling on the page to look good across breakpoints for success stories without a video

### Definition of Done

- [ ] videos can be linked to success stories in the admin UI
- [ ] videos for success stories that have them appear on the website
- [ ] success stories look good at all breakpoints, whether they have videos or not

**Comment by bchiaruttini** [comment]
Completed.
