### ISSUE TITLE
add data validation and required fields to registration forms

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#3]
### as a developer, I need to add data validation and conditionally required fields to the registration form so that we can be sure all required data is being submitted, none of it is malformed
---

### Tasks

- [ ] make all contact 2 fields except occupation required if either the first or last name is filled out
- [ ] add data validation to make sure the **from** age is less than or equal to the **to** age
- [ ] automatically populate the family's information when they try to send their homestudy via email
- [ ] remove any default field and dropdown values that shouldn't exist

### Definition of Done

- [ ] when a contact 2 first or last name is entered, all other contact 2 fields except occupation become required
- [ ] a validation error is displayed if the **from** age is not less than or equal to the **to** age
- [ ] sending homestudy information via email will automatically populate the family's information
- [ ] default field and dropdown values that shouldn't exist have been removed

**Comment by bchiaruttini** [comment]
#3 is fine to work on

**Comment by bchiaruttini** [comment]
no longer valid, working fine.
