### ISSUE TITLE
fix file attachments not displaying in the old system

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#30]
### as a developer, I need to update the website to display attachments when attempting to view them in the old system because there is currently no way to access attachments
---

### Description of the Bug

In the old system, when trying to view attachments, it instead loads the new website into the iFrame where they should be.

### Tasks

- [ ] talk to Brian about gaining access to the old code, or the possibility of redirecting that specific traffic to the attachments page.
- [ ] implement code to display the current attachments for children
- [ ] implement code to display the current attachments for families

### Definition of Done

- [ ] attachments can be accessed via the old system
