### ISSUE TITLE
Fix Sibling Group Size Preference behavior on the child matching dashboard

### ISSUE THREAD

**Issue by n-devr** [mareinc/mare#326]
# Tasks

- [x] Remove the `0` and `Any` options from the `From` dropdown
- [x] Remove `0` from the `To` dropdown
- [x] Ensure that only children translate to a `1` in the `From` dropdown
- [x] Ensure that sibling group sizes greater than 1 are populated to the `From` dropdown accurately
- [x] Ensure that sibling group sizes are matched to family preferences accurately.  Currently, some families with preferences that should logically match a sibling group size are not returned.  E.g. a sibling group size preference of 2-Any does not match a family with a number of children preference of 1-3.
- [x] Update the sibling group size preference to initially populate using the `siblings to be placed with` field from the child model instead of the `siblings field`

**Comment by n-devr** [comment]
Currently the child matching dashboard page is using the `siblings` field of the child model to set the sibling group size preference.  Should we update that to use the `siblings to be placed with` field?

@joesmare
