### ISSUE TITLE
move code to MARE Github account

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#33]
### Tasks

- [x] set up a MARE organization in Github
- [x] create necessary teams and assign team permissions
- [x] create and upload team icons
- [x] transfer code to a repo under the MARE organization
- [x] protect branches and add branch push rules
- [x] set up and connect continuous integration using Travis CI
- [x] update Heroku connections and automatic deployment hooks to point to the new MARE organization
- [x] update Slack hooks to point to the new organzation
- [x] set up the task board

### Definition of Done

- [x] MARE is able to access the new Github organization
- [x] teams are configured
- [x] team icons have been uploaded
- [x] a repo has been created for the website with the most up to date code
- [x] branches have the appropriate level of protection
- [x] continuous integration is set up through Travis CI and MARE can access the dashboard
- [x] Heroku connections are created and branch pushes will automatically deploy if continuous integration checks pass
- [x] Slack displays relevant messages from the new repo in the MARE organzation
- [x] the task board has been created with the necessary columns
