### ISSUE TITLE
transfer Heroku apps to MARE

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#35]
### as a developer, I need to register a Heroku account for MARE and transfer app ownership to it so that MARE has more control over their system
---

### Tasks

- [x] set up a Heroku account for MARE
- [x] transfer ownership of the development app
- [x] transfer ownership of the staging app
- [x] transfer ownership of the production app

### Definition of Done

- [x] MARE is able to access their personal Heroku account
- [x] MARE is able to access the development, staging, and production applications

**Comment by joesmare** [comment]
@autoboxer can @noah make this change? I'd like to start closing some of these older issues. TY
