### ISSUE TITLE
move to MARE owned Amazon S3 buckets

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#36]
### as a developer, I need to register an Amazon account for MARE and point the code there so that MARE has more control over their system
---

### Tasks

- [ ] set up an Amazon account for MARE
- [ ] create a MARE S3 connection
- [ ] set up buckets to line up with targets from each model with S3 fields
- [ ] update the application to point to the MARE owned S3 account

### Definition of Done

- [ ] MARE is able to access their personal Amazon account and S3 bucket
- [ ] files uploaded via the admin UI will be pushed to the correct folder in MARE's S3 account
