### ISSUE TITLE
give admin fine-grained control over event attendees and forms

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#38]
### as a developer, I need to give admin fine-grained control over event attendees and forms so that access to each event can be better controlled by MARE
---

### Tasks

- [ ] add checkboxes to the event model allowing users of each type to attend
- [ ] add checkboxes to the event model allowing social workers to bring registered or unregistered children **[Lisa, should this be one checkbox, or two?]**
- [ ] update events on the website to only allow registration for the selected user types
- [ ] update the event registration form for social workers to only allow bringing children as specified
- [ ] update the event registration form for families to only allow bringing additional adults as specified

### Definition of Done

- [ ] checkboxes are now present in event models in the admin UI to give users specific permissions and access
- [ ] changing the checkboxes for an event have the intended effect on the form for each user type

**Comment by lisa** [comment]
@autoboxer Hi! I think you mean another Lisa. :)

**Comment by autoboxer** [comment]
I do indeed, sorry about that @lisa, I'll remove the mentions.

**Comment by lisa** [comment]
No worries, thanks!

**Comment by joesmare** [comment]
This has been addressed in a different way in the event model work.
