### ISSUE TITLE
connect to MARE owned MailChimp account

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#39]
### as a developer, I need to connect to the MailChimp account for MARE and transfer app ownership to it so that MARE has more control over their system
---

### Tasks

- [ ] update the account with a Mandrill subscriptions
- [ ] generate any necessary API keys
- [ ] add the API key to the development, staging, and production environment variables

### Definition of Done

- [ ] MARE is able to access information about emails in the system via their personal account
- [ ] emails continue to send via Mandrill

**Comment by bchiaruttini** [comment]
Same as #22?

**Comment by joesmare** [comment]
This issue has been completed. There is one adjunct piece that will be added as a separate story.
