### ISSUE TITLE
add complex field validation across all forms

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#4]
### as a developer, I need to add complex field validation across all forms so that users can be presented with more immediate feedback, and data we store in the database will be more consistent.
---

### Tasks

- [ ] add validation for zip code variants
- [ ] add validation for phone number variants
- [ ] add validation for dates
- [ ] add validation for time values

### Definition of Done

- [ ] zip code format is enforced across all forms
- [ ] phone number format variants are enforced across all forms
- [ ] date formats are enforced across all forms
- [ ] time formats are enforced across all forms

**Comment by bchiaruttini** [comment]
per Jared 8/6: #4 is fine to work on, it requires a solid understanding of regular expressions, but there are examples already in the template files for @Arek Jankowski to base his work off of.

maybe duplicate of 14?
