### ISSUE TITLE
transfer domains to DNSimple

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#40]
### Tasks

- [x] unlock domains and request transfer tokens from Network Solutions _( can take up to 3 days )_
- [x] set up a MARE account with DNSimple
- [x] transfer domains to DNSimple _( can take up to 5 days )_
- [x] set up domain forwarding for www.mareinc.org
- [x] set up domain forwarding for mareinc.org
- [x] set up domain forwarding for http://www.mareinc.org
- [x] set up domain forwarding for http://mareinc.org
- [x] set up domain forwarding for www.mareinc.net
- [x] set up domain forwarding for mareinc.net
- [x] set up domain forwarding for http://www.mareinc.net
- [x] set up domain forwarding for http://mareinc.net

### Definition of Done

- [x] MARE has a DNSimple account
- [x] mareinc.org and mareinc.net have been transferred to DNSimple
- [x] domain forwarding sends www.mareinc.org to https://www.mareinc.org
- [x] domain forwarding sends mareinc.org to https://www.mareinc.org
- [x] domain forwarding sends http://www.mareinc.org to https://www.mareinc.org
- [x] domain forwarding sends http://mareinc.org to https://www.mareinc.org
- [x] domain forwarding sends www.mareinc.net to https://www.mareinc.org
- [x] domain forwarding sends mareinc.net to https://www.mareinc.org
- [x] domain forwarding sends http://www.mareinc.net to https://www.mareinc.org
- [x] domain forwarding sends http://mareinc.net to https://www.mareinc.org
