### ISSUE TITLE
set up the new task board

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#41]
### as a Github admin, I need to set up the new MARE task board so that we have a clear representation of all existing issues
---

### Tasks

- [x] create and colorize all labels for the new repo
- [x] create weekly releases to track progress
- [ ] move and clean up all relevant existing issues from the old board
- [ ] move and add details to all relevant issues from the beta spreadsheet
- [ ] add all issues related to data migration of inquiries and placements
- [ ] move and add details to all relevant tasks from Anna's spreadsheet for password issues

### Definition of Done

- [ ] labels are clear and concise
- [ ] weekly releases have been created
- [ ] issues from all available sources have been migrated onto the board
- [ ] all issues have clear Tasks and Definition of Done sections
- [ ] all issues have the appropriate labels applied
