### ISSUE TITLE
style WYSIWYG content

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#42]
### as a developer, I need to add styling to WYSIWYG editor content so that MARE generated pages look good
---

### Tasks

- [ ] add styles for headers
- [ ] add styles for icons
- [ ] add styles for text variants like bold and italics
- [ ] add styles for standard text
- [ ] add styles for paragraphs and content breaks
- [ ] add custom fonts
- [ ] add hooks to add classes to all WYSIWYG elements for targeted styling

### Definition of Done

- [ ] all headers look consistently good
- [ ] all icons look consistently good
- [ ] all text variants look consistently good
- [ ] all standard text look consistently good
- [ ] all standard text look consistently good
- [ ] all paragraphs and content breaks look consistently good
- [ ] custom fonts are being loaded and applied to the page
