### ISSUE TITLE
allow urls to directly access child and sibling group details

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#43]
### as a developer, I need to update the gallery so each child or sibling group can be accessed via a unique url so that child details can be more easily shared, and printing details is made easier
---

### Tasks

- [x] update Express routes to handle child urls
- [x] update Backbone routes to handle child urls
- [x] update details display to process through a Backbone router instead of a Backbone view
- [x] update gallery loading to allow for displaying child details based on a route

### Definition of Done

- [x] child details can be accessed directly via a url
- [x] sibling group details can be accessed directly via a url

**Comment by bchiaruttini** [comment]
per Jared 8/6 - #43 is both too large for consultant.  The complexity requires foundational understanding of how that code works, and the ramp up time alone would be huge.
