### ISSUE TITLE
handle database fetch results better

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#46]
### Tasks

- [ ] update findById() queries to handle empty data sets and invalid id arguments
- [ ] update find() queries to handle empty data sets and invalid id arguments
- [ ] update findOne() queries to handle empty data sets and invalid id arguments

### Definition of Done

- [ ] all findById() queries handle empty data sets and invalid id arguments
- [ ] all find() queries handle empty data sets and invalid id arguments
- [ ] all findOne() queries handle empty data sets and invalid id arguments

**Comment by bchiaruttini** [comment]
still valid, doesn't appear to be an issue, but low risk and low priority

**Comment by n-devr** [comment]
Also includes some elements of #56
