### ISSUE TITLE
make data fetch calls more generic

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#48]
### Tasks

- [ ] update all data fetch calls to use generic versions with optional *populate*, *select*, and *where* clauses if possible
- [ ] remove more specific versions of fetch calls across the codebase
- [ ] return consistent results regardless of missing arguments, no results to return, or results to return

### Definition of Done

- [ ] all data fetch calls have been cleaned up and made as generic as possible

**Comment by joesmare** [comment]
@n-devr this appears to be similiar to #46

**Comment by bchiaruttini** [comment]
still valid, very low risk
