### ISSUE TITLE
replace async with native promises

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#49]
### as a developer, I need to replace async calls with native promises so that we can simplify the code
---

### Tasks

- [ ] replace all async calls with native promises
- [ ] place existing async function calls with calls to generic services
- [ ] remove all references to async

### Definition of Done

- [ ] async has been completely removed from the codebase
- [ ] all unused async related functions have been removed

**Comment by bchiaruttini** [comment]
no longer valid.
