### ISSUE TITLE
autofill event type for social workers submitting events

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#5]
### as a developer, I need to autofill the event type for social workers submitting events so that they have less information to enter
---

### Tasks

- [ ] autofill the event type to **Mapp Training** when a social worker submits an event from a Mapp Training page.
- [ ] autofill the event type to **Agency Information Meeting** when a social worker submits an event from an Agency Information Meeting page.
- [ ] autofill the event type to **Other Opportunities and Training** when a social worker submits an event from an Other Opportunities and Training page.

### Definition of Done

- [ ] logging in as a social worker and submitting an event from any Mapp Training page automatically populates the event type with **Mapp Training**
- [ ] logging in as a social worker and submitting an event from any Agency Information Meeting page automatically populates the event type with **Agency Information Meeting**
- [ ] logging in as a social worker and submitting an event from any Other Opportunities and Training page automatically populates the event type with **Other Opportunities and Training**

**Comment by bchiaruttini** [comment]
per jared 8/6: #5 is fine to work on.  This is best handled via url parameter

**Comment by bchiaruttini** [comment]
no longer relevant.
