### ISSUE TITLE
fix directory structure of server-side code

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#50]
### as a developer, I need to move all server-side code currently in middleware into more appropriate files and folders so that the code is more maintainable
---

### Tasks

- [ ] create a middleware directory and move all true middleware there, fixing any references
- [ ] create an api directory and move all client-side service calls there, fixing any references
- [ ] create a services directory and move all services there, fixing any references

### Definition of Done

- [ ] all server-side code that was in the middleware directory has been broken out into the appropriate file and folder

**Comment by bchiaruttini** [comment]
mostly accomplished so closing.
