### ISSUE TITLE
remove explicit host references in email services

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#51]
### as a developer, I need to remove all explicit host references in email services so that the code is cleaner
---

### Tasks

- [ ] remove all host references
- [ ] ensure host information setting on locals in the main middleware is accessible during templating

### Definition of Done

- [ ] unnecessary host references have been removed

### Notes

there is a host value set in **keystone.js**, which can be accessed via **keystone.get( 'host' )** which may be able to replace host binding in middleware.

**Comment by bchiaruttini** [comment]
higher importance in terms of code quality than others
