### ISSUE TITLE
reduce image bandwidth

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#52]
### as a content manager, I need to reduce image bandwidth across the production site so that we can avoid a $99.00 per month Cloudinary charge
---

### Tasks

- [ ] reduce image size in the gallery
- [ ] reduce image size on the homepage
- [ ] reduce image size in the sidebar

### Definition of Done

- [ ] daily bandwidth doesn't exceed 600 MB ( ideally we can keep the average below 500 MB )
