### ISSUE TITLE
children with siblingGroupImage === null won't display in the admin UI

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#53]
### as a developer, I need to fix an issue with children where their details don't appear in the admin UI when the siblingGroupImage field is set to `null` so that CSCs can always access child details
---

### Description of the Bug

it was discovered that it's possible for the system to save the `siblingGroupImage` field for one child in a sibling group with a value of `null`, while the other has a value of `undefined`.  The `null` value is preventing the child's details from loading in the admin UI.

### Tasks

- [ ] determine what causes a `null` value in the `siblingGroupImage` field
- [ ] update the code to prevent `null` values in the `siblingGroupImage` field

### Definition of Done

- [ ] problematic child details appear in the admin UI
- [ ] `null` values are no longer being saved to children records in the siblingGroupImage field

### Notes

this was discovered in child 6791 who had a null value in the siblingGroupImage field, however, his sibling 6792 didn't have a value set for the field.
