### ISSUE TITLE
fix handling of empty data request results

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#56]
### as a developer, I need to better handle empty data request results so that the code is more predictable
---

### Tasks

- [ ] update all `findById()` functions to process empty results by returning `undefined` through the success block instead of the error block
- [ ] update all findOne() functions to process empty sets by returning `undefined` through the success block instead of the error block
- [ ] update all `find()` functions to process empty results by returning an empty array through the success block instead of the error block
- [ ] update all `Promise` scaffolding that calls data fetch functions with handling for empty results

### Definition of Done

- [ ] all fetch functions handle empty results through the success block

**Comment by bchiaruttini** [comment]
redudant of 46 so closing
