### ISSUE TITLE
handle bad routes

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#57]
### as a developer, I need to handle bad routes so that the user is always presented with an appropriate page
---

### Tasks

- [x] send unknown routes to the 404 page
- [x] handle server errors (500s)

### Definition of Done

- [x] nonsensical routes display the 404 page for the user
- [x] server errors display the 500 page for the user

**Comment by bchiaruttini** [comment]
still valid and higher priority

**Comment by n-devr** [comment]
Design/UI considerations are covered in #71
