### ISSUE TITLE
Account Verification Enhancements

### ISSUE THREAD

**Issue by n-devr** [mareinc/mare#591]
## Tasks
 - [x] Update account verify behavior to force the user to click a "Verify" button instead of basing verification on the page visit.  This was causing issues due to Outlook visiting the page with the BingPreview bot before the user actually clicked on the link.  ([Issue](https://stackoverflow.com/questions/41699071/bingpreview-invalidates-one-time-links-in-email))
- [x] Make account verification mandatory before first login.
    - [x] Do not automatically sign users in upon successful registration
    - [x] Display a flash message to users directing them to open their email and verify
    - [x] Do not allow unverified accounts to log in
    - [x] Add a flash message to login flow for unverified users
 - [x] Don't delete verification codes that have already been exchanged.
 - [x] Create messaging around "expired" verification codes (to prevent confusion from errors being thrown for repeated verification attempts)

**Comment by n-devr** [comment]
Tasks per review with @bchiaruttini :

 - [ ] when inactive users activate their account via password reset flow, mark them verified as well
 - [ ] update all current 'active' users to be verified
 - [ ] update verified status when admin changes active status from false -> true in the admin ui

**Comment by bchiaruttini** [comment]
I have a question about the account verification error messages that we can discuss on Wed.  thanks.
