### ISSUE TITLE
check all model save functions for errors on missing required field data

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#61]
### as a developer, I need to ensure all calculated required fields are being populated so that errors aren't thrown when creating new models
---

### Tasks

- [ ] option 1: make all fields we calculate from required across all modes
- [ ] option 2: handle failures gracefully, setting required derived fields we can't calculate to default values

### Definition of Done

- [ ] model creation doesn't fail when not enough information is given to calculate derived field values

**Comment by bchiaruttini** [comment]
not feasible
