### ISSUE TITLE
assigning siblings/siblings to be placed when creating a Child record crashes the app

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#62]
### as a developer, I need to fix a bug that crashes the app when siblings or siblings to be placed with are assigned to a child record while it's being created so that the system is more stable and CSCs aren't prevented from doing their work
---

### Bug Details

doing the following will cause the website to crash:

1. log in as an **admin**
2. create a new child record, filling in all required fields, and ensuring that selections are made in both the **siblings** and **siblings to be placed with** fields.

### Tasks

- [x] identify what's causing the error
- [x] fix the bug

### Definition of Done

- [ ] running through the steps in **bug details** will no longer crash the app

#### 1. running through the steps in **bug details** will no longer crash the app

1. log in as an **admin**
2. navigate to development.adoptions.io/keystone/children and click the button to create a new child
3. fill in all required fields, and ensure that selections are made in both the **siblings** and **siblings to be placed with** fields
4. click the **save** button
5. note that the website doesn't crash

### Notes

The error is thrown on line **281** in **models/Child.js**:

`this.siblingsToBePlacedWith = this._original.siblingsToBePlacedWith;`
