### ISSUE TITLE
speed up logo loading for all public emails

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#63]
### as a developer, I need to speed up the loading of the MARE logo in emails the public may see so that the email appears to load completely as it's opened
---

### Tasks

- [ ] follow the example of inquiry emails to MARE, there is a `logo` variable set on the `email locals` which is a base-64 encoded version of the logo.  This should be directly referenced in the email template
- [ ] remove all references to host where applicable.  Note that host is set in `email locals`, and doesn't need to be recalculated anywhere if it's being used for emails

### Definition of Done

- [ ] all emails with the MARE logo load instantly when opened

**Comment by bchiaruttini** [comment]
likely already done @noah will verify

**Comment by n-devr** [comment]
It looks like most email clients (Outlook and GMail) will block embedded images by default ([source](https://www.campaignmonitor.com/blog/email-marketing/embedded-images-in-html-email/)).  I don't think this is worth looking into any further - the current approach allows the images to load if the user has images enabled, whereas if we try to embed the image it will never load.
