### ISSUE TITLE
create a Github readme file

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#64]
### Tasks

- [ ] create the readme.md file
- [ ] add license information
- [ ] add contributing information
- [ ] add installation instructions

### Definition of Done

- [ ] the readme.md file has been created with license information, contributing instructions, and installation instructions

**Comment by bchiaruttini** [comment]
still valid, low priority
