### ISSUE TITLE
upgrade Keystone to 4.x

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#65]
### as a developer, I need to upgrade Keystone to the 4.x branch to allow for security patches and to improve the admin UI experience
---

### Tasks

- [x] upgrade Keystone to the latest version
- [x] follow [the upgrade instructions](1) to convert deprecated fields
- [x] follow [the upgrade instructions](1) to update app scaffolding

### Definition of Done

- [x] the app launches
- [x] all models can be created/edited/deleted without issue
- [x] all website pages and components display correctly

### Known Issues

1. date format isn't working for fields
2. if the field mapped to **name** in a model is a relationship, clicking on it brings the user to the related item instead of to the model
3. if the field mapped to name isn’t first in default columns, it can’t be clicked to open the model
4. creating a new model opens a modal that’s larger than the screen and not scrollable when there are more fields than will fit on screen

[1]: (https://github.com/keystonejs/keystone/blob/master/docs/guides/v0.3-to-v4.0-Upgrade-Guide.md)
