### ISSUE TITLE
make child registration form printable

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#67]
### as a developer, I need to make the child registration form printable for social workers so that they aren't restricted to providing information through the website
---

### Tasks

- [ ] add a print button to the page
- [ ] create a print stylesheet for the page

### Definition of Done

- [ ] clicking on the print button initiates a print operation
- [ ] printing through the browser initiates a print operation
- [ ] the child registration form can be printed in a clean, readable way

**Comment by bchiaruttini** [comment]
No longer necessary.
