### ISSUE TITLE
auto-update cross-model derived fields

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#68]
### as a developer, I need to implement cross model saving for derived fields so that models won't display stale information prior to saving
---

### Tasks

- [ ] identify all cross-model derived fields
- [ ] update post-save hooks in all referenced models to either broadcast an event which can be handled in middleware, or explicitly save any referencing models.  Alternatively, these fields can be made into virtuals, storing the referenced model in a hidden field if necessary

### Definition of Done

- [ ] all models which have values calculated from other models update automatically without the need to resave

**Comment by bchiaruttini** [comment]
not needed, too complex.
