### ISSUE TITLE
handle bad url paths

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#69]
### as a developer, I need to handle bad urls better so that we can fail gracefully where possible, and route to a 404 page where necessary
---

### Tasks

- [ ] update the main router with bad url handling
- [ ] update each child router with bad url handling

### Definition of Done

- [ ] bad urls route appropriately
