### ISSUE TITLE
fix file uploads for Keystone models

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#7]
### as a developer, I need to fix file uploads in Keystone so that files can be attached to models
---

### Tasks

- [ ] get file uploads working for Child attachments
- [ ] ensure all child attachments are stored in the correct folder of the S3 bucket
- [ ] get file uploads working for Family attachments
- [ ] ensure all family attachments are stored in the correct folder of the S3 bucket

### Definition of Done

- [ ] files can be attached to child records
- [ ] files can be attached to family records

**Comment by bchiaruttini** [comment]
per jared 8/6: #7 should be put off as it’s migration code that I should handle personally after upgrading Keystone.

**Comment by autoboxer** [comment]
@bchiaruttini, I'm still looking into what's causing the crash, but the file fields for both Child and Family are ready to test (I was hiding the homestudy file upload for Family, but fixed that).  The crash has to do with Cloudinary Images, so as long as you're not changing image fields, you should be able to test this.
