### ISSUE TITLE
create custom 404 page

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#70]
### as a developer, I need to create a custom 404 'page not found' page so that we can handle bad url requests gracefully
---

### Tasks

- [x] create the 404 page
- [x] style all responsive variants of the page
- [x] update bad routes to redirect to the 404 page

### Definition of Done

- [x] the 404 exists
- [x] appropriate bad url paths direct the user to the 404 page
- [x] the page looks good at all screen widths

**Comment by bchiaruttini** [comment]
valid, reference #57
