### ISSUE TITLE
design custom 404 page

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#71]
### as a designer, I need to create a custom 404 page so that we have a nice looking page to route the user to where necessary
---

### Tasks

- [ ] design the full-size 404 page
- [ ] design responsive variants to the 404 page

### Definition of Done

- [ ] a Sketch document exists with the specs for styling the custom 404 page at all screen widths

**Comment by joesmare** [comment]
Captured overalp with #70 and consolidated
