### ISSUE TITLE
update inquiry flowchart

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#72]
### as a documenter, I need to update the inquiry flowchart so that we have clear documentation showing how the inquiry system works
---

### Tasks

- [ ] review the code with Lisa to ensure all branches in the logic are correct
- [ ] update the flowchart with any needed changes

### Definition of Done

- [ ] the inquiry flowchart represents the correct logic for inquiry handling

**Comment by joesmare** [comment]
Logic tree should include all actionable branches. At the conclusion of this project a map should  be generated so that any user or future contractor can understand the logic behind the routing and decision making process. This may be a project for a future in-house developer and can be used to familiarize the person with the system.

**Comment by joesmare** [comment]
This should be part of the cross-over work as it will support @n-devr in his engagement

**Comment by bchiaruttini** [comment]
still valid
