### ISSUE TITLE
add headers to sidebar cards

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#74]
### as a developer, I need to add headers to the sidebar cards so that the content is more clear to users of the site
---

### Tasks

- [ ] add success story header
- [ ] add event card header

### Definition of Done

- [ ] the success story and event cards in the sidebar both have clear headers

**Comment by joesmare** [comment]
@n-devr we are now calling 'Success Stories' as 'Adoption Stories'. Change header language accordingly.

**Comment by bchiaruttini** [comment]
jeremy is able to complete
