### ISSUE TITLE
update site forms

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#75]
### as a developer, I need to update forms across the site so they are more usable and look nicer
---

### Tasks

- [ ] pick a new form library that has a cleaner display and better handling for fields like dates and phone numbers ( consider material design )
- [ ] update the site visitor registration form
- [ ] update the social worker registration form
- [ ] update the family registration form
- [ ] update the have a question form
- [ ] update the information request form
- [ ] update the event registration form
- [ ] update the social worker child registration form
- [ ] update the social worker family registration form

### Definition of Done

- [ ] the site visitor registration form has been updated with the new look and functionality
- [ ] the social worker registration form has been updated with the new look and functionality
- [ ] the family registration form has been updated with the new look and functionality
- [ ] the have a question form has been updated with the new look and functionality
- [ ] the information request form has been updated with the new look and functionality
- [ ] the event registration form has been updated with the new look and functionality
- [ ] the social worker child registration form has been updated with the new look and functionality
- [ ] the social worker family registration form has been updated with the new look and functionality
- [ ] data validation works on the site visitor registration form
- [ ] data validation works on the social worker registration form
- [ ] data validation works on the family registration form
- [ ] data validation works on the have a question form
- [ ] data validation works on the information request form
- [ ] data validation works on the event registration form
- [ ] data validation works on the social worker child registration form
- [ ] data validation works on the social worker family registration form

**Comment by joesmare** [comment]
There are aspects of this work that have been completed with other tasks. Review list before working on this story.

**Comment by bchiaruttini** [comment]
no longer relevant
