### ISSUE TITLE
fix character encoding in model Relationship lists

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#76]
### as a developer, I need to fix text encoding in the relationship lists at the bottom of records so that the text is more readable
---

### Tasks

- [ ] update Keystone's display of Relationship text fields to prevent character encoding.

### Definition of Done

- [ ] whitespace is preserved in Relationship fields displayed at the bottom of models
- [ ] special characters aren't encoded in Relationship fields displayed at the bottom of models

### Notes

With support ending for Keystone 0.3.x, this will need to wait until we've upgraded to the 4.x branch.  Once done, the fix must be handed in the [Keystone code](https://github.com/keystonejs/keystone)

**Comment by bchiaruttini** [comment]
per jared 8/6: #76 may be fixed when we upgrade versions of Keystone, so I’d hold off on that as well.

**Comment by bchiaruttini** [comment]
resolved with 4.0 upgrade.
