### ISSUE TITLE
update MLab environments

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#77]
### as a developer, I need to update the MLab setup for development and staging so that cost can be minimized and there is a clear strategy to pull down data from production as needed
---

### Tasks

- [ ] move development to the free plan
- [ ] move staging to the paid plan
- [ ] determine what data can be omitted from the development server to keep it free

### Definition of Done

- [ ] the mLab development server is on a free plan and not exceeding it's data cap
- [ ] the mLab staging server is on a paid plan
