### ISSUE TITLE
document mLab administration

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#78]
### as a developer, I need to document MLab process and features so that future mLab administrators know how to perform all basic tasks
---

### Tasks

- [ ] document accounts and roles
- [ ] document exporting tables
- [ ] document exporting a full database backup
- [ ] document importing tables
- [ ] document importing a full database backup
- [ ] document common queries

### Definition of Done

- [ ] documentation is available as a PDF
- [ ] documentation for mLab administration is complete and easy to read

**Comment by bchiaruttini** [comment]
no longer using MLab
