### ISSUE TITLE
document git branching and deployment strategy

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#79]
### as a developer, I need to document git branching and deployment strategy so that developers know how to contribute and senior developers know how to promote and rollback code
---

### Tasks

- [ ] document feature branch use
- [ ] document branch merging for development
- [ ] document branch merging for staging
- [ ] document branch merging for production
- [ ] document omitting branches in a merge
- [ ] document handling of incomplete or error-prone branch code
- [ ] document tagging
- [ ] document versioning

### Definition of Done

- [ ] documentation is available as a PDF
- [ ] documentation for git branching and deployment strategy is complete and easy to read

### References

[Branch per Feature - Adam Dymitruk](http://dymitruk.com/blog/2012/02/05/branch-per-feature/)

**Comment by joesmare** [comment]
@n-devr please document git branching so that we have it mapped for any future developers?

**Comment by bchiaruttini** [comment]
still valid.
