### ISSUE TITLE
Persist column visibility settings between searches on reporting dashboard

### ISSUE THREAD

**Issue by n-devr** [mareinc/mare#802]
### as a user, I want my column visibility settings for a report to persist between searches, so that I don't have to update my settings every time I update my search criteria.  I also want to be able to share a link with my column settings specified.
---

### Tasks

- [x] persist the column visibility settings in URL parameters
- [x] parse the column visibility settings from URL params and apply them to the grid

### Definition of Done

- [ ] column visibility settings persist between searches
- [ ] copying a link and opening it a new page also persists column visibility settings
