### ISSUE TITLE
remove duplicate siblings and siblings to be placed with

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#81]
### as a developer, I need to remove duplicate siblings and siblings to be placed with fields for all children so that there isn't unexpected behavior when removing entries from either
---

### Tasks

- [ ] use the **fix** branch to find all children with duplicate sibling or siblings to be placed with
- [ ] use the **fix** branch to loop over all children, converting the siblings and siblings to be placed with entries to sets, then back to arrays

### Definition of Done

- [ ] removing previously duplicate sibling entries will update the record correctly
- [ ] removing previously duplicate sibling entries will update all sibling records correctly
- [ ] removing previously duplicate siblings to be placed with entries will update the record correctly
- [ ] removing previously duplicate siblings to be placed with entries will update all siblings to be placed with records correctly

**Comment by bchiaruttini** [comment]
Per Jared 8/6 - #81 should already be fixed, and doesn’t affect what you see in the admin UI anyway.  I can test this after the upgrade to see if it’s still an issue.

**Comment by bchiaruttini** [comment]
tested and resolved
