### ISSUE TITLE
change response codes

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#82]
### as a developer, I need to change the HTTP status codes to the correct number for each response so that the code is easier to understand
---

### Tasks

- [ ] update all 2xx status codes
- [ ] update all 3xx status codes
- [ ] update all 4xx status codes
- [ ] update all 5xx status codes

### Definition of Done

- [ ] all status codes have been correctly updated across the site

### Resources

[HTTP Status Codes](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes)

**Comment by bchiaruttini** [comment]
still valid, lower priority, longer term investment
