### ISSUE TITLE
update the general and child inquiry emails

### ISSUE THREAD

**Issue by bchiaruttini** [mareinc/mare#84]
### as a developer, I need to update the contents of the general and child inquiry emails so that the information is more clear for CSCs
---

### Tasks

- [ ] update the logo to always display.  It was noted that it doesn't display on desktop, but does on mobile ( this could have to do with the email client settings )
- [ ] remove the statement **"The inquiry will need to be reviewed and some fields......"**
- [ ] update the contact info for family inquiries as follows:
    - [ ] if there is only a contact 1, display the info as is, without a contact header
    - [ ] if there are two contacts, add contact 1 and contact 2 headers, and display all current fields for both contacts
- [ ] add fields for social worker agency and social worker contact information to family inquiries
- [ ] display only the most recent stage under steps in the process.  The most recent date (to the day) should take precedence, and if two stages have the same date, it should use the stage that's furthest along in the process.
- [ ] add homestudy completed to the calculated options under steps in the process.

### Definition of done

- [ ] the logo to always display in desktop email clients
- [ ] the statement **"The inquiry will need to be reviewed and some fields......"** has been removed
- [ ] the contact info for family inquiries has been updated as follows:
    - [ ] if there is only a contact 1, the info is displayed as is, without a contact header
    - [ ] if there are two contacts, contact 1 and contact 2 headers are present, and all fields are displayed for both contacts
- [ ] fields for social worker agency and social worker contact information have been added to family inquiries
- [ ] only the most recent stage is displayed under steps in the process.  The most recent date (to the day) takes precedence, and if two stages have the same date, it shows the stage that's furthest along in the process.
- [ ] homestudy completed has been added to the calculated options under steps in the process.

**Comment by autoboxer** [comment]
I'd recommend having @arek-neptuneweb work on everything except the first item.  The logo update with testing is bound to turn into a time sink.

**Comment by bchiaruttini** [comment]
Please also add family registration number as a field that displays on email.
