### ISSUE TITLE
prevent items in the sidebar from loading content for the current page

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#86]
### as a developer, I need to prevent the sidebar from loading items about the current page so that users have a better experience
---

### Tasks

- [ ] prevent the random event from fetching the current page when viewing an event
- [ ] prevent the random success story from fetching the current page when viewing a success story

### Definition of Done

- [ ] the sidebar never loads an event matching the current page for the event box
- [ ] the sidebar never loads a success story matching the current page for the success story box
