### ISSUE TITLE
migrate placements

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#9]
### Tasks

- [x] import placements from the old system, branching out matches, placements, legalizations and disruptions into the newly created models for each.
- [x] import sources, which should only be applied to the latest record for matches, placements, disruptions, and legalizations.
- [x] fix the family agency field so it’s always there, no matter if the family is registered in the system or not.
- [x] add agency for registered families automatically when we fetch their record.  Apply the agency to all records associated with them, not just the latest.
- [x] ensure duplicates are not being created.

### Definition of Done

- [x] placements have been imported from the old system and created as matches, placements, legalizations, and disruptions depending on the information contained in each.
- [x] the family agency field is present whether the family is registered with MARE or not
- [x] placements have a family agency listed for all records with a registered family who has a social worker listed.
- [x] sources are present for the most recent match, placement, legalization, and disruption for a particular child.
- [x] there are no duplicates in the system.
