### ISSUE TITLE
migrate from gulp to webpack

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#90]
### as a developer, I need to move our build process from gulp to webpack so that we have a more robust build process
---

### Tasks

- [ ] set up the dist target location
- [ ] set up file concatenation step
- [ ] set up code uglification step
- [ ] set up image optimization step
- [ ] set up sass preprocessing step
- [ ] set up font building step
- [ ] set up any additional tasks such as uncss, treeshaking, etc.
- [ ] set up an npm/yarn build task
- [ ] update heroku build step to use webpack

### Definition of Done

- [ ] all local front-end code is processed through webpack
- [ ] Heroku deployments process all front-end code through webpack

**Comment by bchiaruttini** [comment]
still valid, higher priority, but monster of a project.   Gulp is not broken but outdated.  Migrating to webpack would put it into modern frameworks and make future changes much easier.
