### ISSUE TITLE
implement GraphQL for data access

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#92]
### as a developer, I need to implement GraphQL for data access so that queries can be cleaned up, time can be saved, and overfetching data isn't a problem
---

### Tasks

- [ ] implement GraphQL schemas for all model data fetches
- [ ] implement GraphQL schemas for all service data fetches
- [ ] implement GraphQL schemas for all middleware data fetches
- [ ] implement GraphQL schemas for all controller data fetches
- [ ] implement GraphQL queries for all model data fetches
- [ ] implement GraphQL queries for all service data fetches
- [ ] implement GraphQL queries for all middleware data fetches
- [ ] implement GraphQL queries for all controller data fetches

### Definition of Done

- [ ] all data fetch functions have an associated GraphQL schema present
- [ ] all data fetch functions use GraphQL for data access
