### ISSUE TITLE
allow admin to prevent registration for events

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#93]
### as a developer, I need to add a mechanism to prevent registration for events so that MARE can post events to the website that don't allow users to register
---

### Tasks

- [x] add a checkbox to the event model
- [x] adjust the events list page template to prevent registration for any events that don't allow it
- [x] adjust the event details page template to prevent registration if the event doesn't allow it

### Definition of Done

- [ ] a new **prevent registration** access control is present in the event model
- [ ] selecting **prevent registration** for an event removes the registration button for that event on the events list page
- [ ] selecting **prevent registration** for an event removes the registration button for that event on the event details page
- [ ] events without **prevent registration** selected still have registration active on the events list page
- [ ] events without **prevent registration** selected still have registration active on the event details page

#### setup

1. log in as a **family**
2. navigate to development.adoptions.io/events/adoption-parties and note that all events allows registration
3. click on **view details** for an event and note that registration is allowed on the event details page
4. log out and log is as an **admin** user

#### 1. a new prevent registration access control is present in the event model

1. navigate to development.adoptions.io/keystone/events and open an active **adoption party** event
2. note that there is checkbox labeled **prevent registration** in a new section titled **Access Restrictions**

#### 2. selecting prevent registration for an event removes the registration button for that event on the events list page

1. check the **prevent registration** checkbox for the event and click **save**
2. log out
3. log in as a family
4. navigate to development.adoptions.io/events/adoption-parties
5. note the event with *prevent registration* checked no longer has the register/unregister button available

#### 3. selecting **prevent registration** for an event removes the registration button for that event on the event details page

1. click **view details** for the event that has **prevent registration** checked
2. note that the register/unregister button is no longer present

#### 4. events without **prevent registration** selected still have registration active on the events list page

1. navigate to development.adoptions.io/events/adoption-parties
2. note an event without the **prevent registration** checkbox checked has a register/unregister button available

#### 5. events without **prevent registration** selected still have registration active on the event details page

1. click **view details** for an event without **prevent registration** selected
2. note that the register/unregister button is available

### Test Accounts

family email: testfamily@mare.com
password: asdf
