### ISSUE TITLE
social workers unregistering from an event when a child with no recruitment worker is attending crashes the website

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#95]
### as a developer, I need to fix a bug causing the app to crash when a social worker unregisters from an event so that the website is more stable
---

### Bug Details

if the following conditions are met, the website will crash:

1. a social worker registers for an event with one or more children already in the system
2. an admin adds a child who doesn't have a recruitment worker to the same event
3. the social worker attempts to unregister from the event

### Tasks

- [x] update the event service to check for existence of a recruitment worker when adding/removing registered children from an event
- [x] update error handling for adding/removing children from an event to catch errors for each asynchronous task in the process

### Definition of Done

- [ ] running through the steps in **bug details** will no longer crash the app

#### 1. running through the steps in **bug details** will no longer crash the app

1. log in as a **social worker**
2. navigate to development.adoptions.io/events/adoption-parties and register for an event, being sure to add at least one registered child in the process
3. log out
4. log is as an **admin** user
5. open a child record
6. remove the adoption worker and save the child record
7. navigate to the event the Social Worker registered for in the admin UI
8. add the child you updated in **step 6** new child to the event
9. log out
10. log in as the same **social worker** from **step 1**
11. navigate to development.adoptions.io/events/adoption-parties and unregister from the event you registered for in **step 2**
12. note that the website doesn't crash

### Test Accounts

social worker email: testsocialworker@mare.com
password: asdf
