### ISSUE TITLE
update MAPP training intro

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#96]
### as a developer, I need to update the intro to MAPP training events so that users are presented with more useful information
---

### Tasks

- [x] add the information outlined in the **details** section to the MAPP training intro section

### Definition of Done

- [ ] the information in the **details** section has been added to the intro for the MAPP training events list page
- [ ] the information in the **details** section has been added to the intro for the MAPP training event details page

### Details

![MAPP Training Intro.png](https://images.zenhubusercontent.com/5726c04cbf93871ccd9a55e6/27ff1e71-4fcf-4c20-aa43-27e27a4ae30a)

#### 1. the MAPP Training event list page has the new intro information

1. navigate to https://www.mareinc.org/events/mapp-trainings/
2. note that the updated intro is present

#### 2. the MAPP Training event details page has the new intro information

1. navigate to https://www.mareinc.org/events/mapp-trainings/dcf-boston-training
2. note that the updated intro is present
