### ISSUE TITLE
agency and agency regions aren't clearing when a recruitment worker or adoption worker is removed from a child's record

### ISSUE THREAD

**Issue by autoboxer** [mareinc/mare#97]
### as a developer, I need to fix a bug preventing the agency and agency region fields from automatically clearing out when the associated worker is removed from a child's record so that the child's information is as accurate as possible
---

### Tasks

- [x] update the child record to clear out the adoption worker agency information when the adoption worker is removed from a child's record
- [x] update the child record to clear out the recruitment worker agency information when the recruitment worker is removed from a child's record

### Definition of Done

- [ ] the adoption worker agency information is removed when the adoption worker is removed from a child's record
- [ ] the recruitment worker agency information is removed when the recruitment worker is removed from a child's record

#### setup

1. log in as an **admin**
2. open up a child's record in the admin UI

#### 1. the adoption worker agency information is removed when the adoption worker is removed from a child's record

1. if an adoption worker is not already saved for the child, add an adoption worker and save the child's record
2. note that the adoption worker agency and adoption worker agency region fields are populated
3. remove the adoption worker and save the child's record
4. note that the adoption worker agency and adoption worker agency region fields are no longer populated

#### 2. the recruitment worker agency information is removed when the recruitment worker is removed from a child's record

1. if an recruitment worker is not already saved for the child, add a recruitment worker and save the child's record
2. note that the recruitment worker agency and recruitment worker agency region fields are populated
3. remove the recruitment worker and save the child's record
4. note that the recruitment worker agency and recruitment worker agency region fields are no longer populated
