### ISSUE TITLE
Remove Bookmarked Profiles When Child Status is Inactive

### ISSUE THREAD

**Issue by bchiaruttini** [mareinc/mare#99]
### as a user, I need children with statuses other than active to be removed from my bookmark list so I have a better idea of which children are available, and which are not
---

### Tasks

- [ ] add a function in the pre-save hook for children to check the status of the child, and if it's something other than active, find all families with that child bookmarked and remove them from the list
- [ ] update the family account page tab for bookmarked children to include the following message:
    >You can bookmark specific child/sibling profiles to track children you have inquired about or wish to inquire about.  Please note that once a child's status is no longer active they will be removed from your Bookmarked Profiles list.

### Definition of Done

- [ ] children with a status of active will appear as bookmarked by families in their account page
- [ ] children with a status of disrupted will no longer appear as bookmarked by families in their account page
- [ ] children with a status of on hold will no longer appear as bookmarked by families in their account page
- [ ] children with a status of placed will no longer appear as bookmarked by families in their account page
- [ ] children with a status of reunification will no longer appear as bookmarked by families in their account page
- [ ] children with a status of withdrawn will no longer appear as bookmarked by families in their account page

**Comment by autoboxer** [comment]
@bchiaruttini, a little clarification is needed for this story.  Consider the following scenario:

1. **child a** has their status set to **active**
2. **family b** bookmarks **child a**
2a. at this point **child a** shows up as bookmarked in **family b**'s account page
3. **child a**'s status is changed to **disrupted**
3a. at this point **child a** doesn't show up as bookmarked in **family b**'s account page
4. **child a**'s status is changed back to **active**

should **child a** automatically be added back to **family b**'s bookmarked children in their account page, or should the removal be permanent?

**Comment by bchiaruttini** [comment]
Yes, good question.  The bookmarked profile should automatically be added back to the family’s list should they become reactive again. thanks.
